import { init } from "@paralleldrive/cuid2";
import * as z from "zod";

export const CUID_LENGTH = 16;
export const CUID_PREFIXES = [
  "evt", // event_type
  "intv", // interviewer
  "rule", // availability_rule
  "exc", // availability_exception
  "book", // booking
  "invt", // invite
] as const;
export type CuidPrefix = (typeof CUID_PREFIXES)[number];

export const createId = (prefix: CuidPrefix, length = CUID_LENGTH) =>
  `${prefix}_${init({ length })()}`;

export const createCode = () => {
  const cuid = init({ length: 4 });
  return `${cuid()}-${cuid()}-${cuid()}`;
};

/**
 * Zod custom type that parses and validates CUIDs generated by createId (from @paralleldrive/cuid2)
 * Accepts optional prefix and length for custom CUID formats
 */
export const zCuid = (prefix: CuidPrefix, length = CUID_LENGTH) =>
  z.custom<string>(
    (val) => typeof val === "string" && new RegExp(`^${prefix}_[a-z0-9]{${length}}$`).test(val),
    {
      message: `Must be a valid CUID2${prefix ? ` with prefix '${prefix}'` : ""} and length ${length + (prefix ? prefix.length + 1 : 0)}`,
    },
  );
